services:
  frontend:
    image: node:22.15.0-alpine
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: votify-back:0.0.1
    ports:
      - "8090:8080"
      - "8000:8000"
    environment:
      - POSTGRE_HOST=${DB_HOST}
      - POSTGRE_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      flyway:
        condition: service_completed_successfully

  flyway:
    image: flyway/flyway:10
    command: -url=jdbc:postgresql://${DB_HOST}:${DB_FLYWAY_PORT}/${DB_NAME}?sslmode=require&prepareThreshold=0 -user=${DB_USER} -password=${DB_PASSWORD} -baselineOnMigrate=true -baselineVersion=1 migrate
    volumes:
      - ./migrations:/flyway/sql
    restart: on-failure