services:
  db:
    image: postgres:16
    container_name: votify_bd
    environment:
      POSTGRES_DB: Votify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: node:22.15.0-alpine
    command: sh -c "while true; do sleep 3600; done"
    working_dir: /app
    ports:
        - 127.0.0.1:3000:3000
    volumes:
        - ./frontend:/app
    environment:
        - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: