spring.application.name=backend

spring.config.import=optional:file:../.env

spring.datasource.url=jdbc:postgresql://${POSTGRE_HOST:localhost}:${POSTGRE_PORT:5433}/${POSTGRES_DB:votify}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

admin.email=${ADMIN_EMAIL:admin@votify.com}
admin.password=${ADMIN_PASSWORD:admin123}
admin.nombre=${ADMIN_NOMBRE:admin}

spring.jpa.hibernate.ddl-auto=validate
spring.jackson.default-property-inclusion=always

server.error.include-message=always