spring.application.name=backend

spring.config.import=optional:file:../.env

spring.datasource.url=jdbc:postgresql://${POSTGRE_HOST:aws-0-eu-west-1.pooler.supabase.com}:${POSTGRE_PORT:5432}/${POSTGRES_DB:postgres}?sslmode=require
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

admin.email=${ADMIN_EMAIL:admin@votify.com}
admin.password=${ADMIN_PASSWORD:admin123}
admin.nombre=${ADMIN_NOMBRE:admin}

spring.jpa.hibernate.ddl-auto=validate
spring.jackson.default-property-inclusion=always

server.error.include-message=always

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

gemini.api-key=AIzaSyBEPfDELTv7PjTbkd4MDgdeB4ha_jdN7GI
gemini.model=${GEMINI_MODEL:gemini-2.0-flash}
gemini.generate-url=${GEMINI_GENERATE_URL:https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent}