spring.application.name=backend

spring.config.import=optional:file:../.env

spring.datasource.url=jdbc:postgresql://${POSTGRE_HOST:localhost}:${POSTGRE_PORT:5433}/${POSTGRES_DB:votify}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jackson.default-property-inclusion=always